language: php
php:
 - 5.3

env:
  matrix:
   - DB=MYSQL CORE_RELEASE=3.2

matrix:
  include:
    - php: 5.3
      env: DB=MYSQL CORE_RELEASE=3.2
    - php: 5.4
      env: DB=MYSQL CORE_RELEASE=3.2
    - php: 5.5
      env: DB=MYSQL CORE_RELEASE=3.3
    - php: 5.6
      env: DB=MYSQL CORE_RELEASE=3
    - php: 5.6
      env: DB=MYSQL CORE_RELEASE=3.2
    - php: 5.6
      env: DB=PGSQL CORE_RELEASE=3.3

before_script:
 - phpenv rehash
 - git clone git://github.com/silverstripe-labs/silverstripe-travis-support.git ~/travis-support
 - php ~/travis-support/travis_setup.php --source `pwd` --target ~/builds/ss
 - cd ~/builds/ss

script:
 - vendor/bin/phpunit steamedclams/tests/
